In [12]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [13]:
data = pd.read_csv('train.csv')
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [21]:
data = np.array(data)
m, n = data.shape # get dimensions of data
np.random.shuffle(data) # shuffle the data

data_dev = data[0:1000].T
y_dev = data_dev[0]
X_dev = data_dev[1:n]

data_train = data[1000:m].T
X_train = data_train[1:n]
y_train = data_train[0]

X_train = X_train / 255
_, m_train = X_train.shape

In [46]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLu(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    return np.exp(Z) / np.sum(np.exp(Z))

def one_hot(y):
    one_hot_y = np.zeros((y.size, y.max() + 1))
    one_hot_y[np.arange(y.size), y] = 1
    return one_hot_y.T

def deriv_ReLu(Z):
    return Z > 0

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLu(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def back_prop(Z1, A1, Z2, A2, W1, W2, X, y):
    one_hot_y = one_hot(y)
    dZ2 = A2 - one_hot_y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)

    dZ1 = W2.T.dot(dZ2) * deriv_ReLu(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)

    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2


In [38]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, y):
    print(predictions, y)
    return np.sum(predictions == y) / y.size

def gradient_descent(X, y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W1, W2, X, y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)

        if i % 10 == 0:
            print("Iterations: ", i)
            print("Accuracy: ", get_accuracy(get_predictions(A2), y))
    return W1, b1, W2, b2

### Training Accuracy ###

In [42]:
W1, b1, W2, b2 = gradient_descent(X_train, y_train, 500, 0.1)

Iterations:  0
[2 3 2 ... 1 2 2] [9 4 6 ... 2 0 7]
Accuracy:  0.0945609756097561
Iterations:  10
[2 2 2 ... 1 0 2] [9 4 6 ... 2 0 7]
Accuracy:  0.1982439024390244
Iterations:  20
[7 2 2 ... 1 0 2] [9 4 6 ... 2 0 7]
Accuracy:  0.25565853658536586
Iterations:  30
[7 3 4 ... 1 0 9] [9 4 6 ... 2 0 7]
Accuracy:  0.31441463414634147
Iterations:  40
[7 4 4 ... 1 0 9] [9 4 6 ... 2 0 7]
Accuracy:  0.3758780487804878
Iterations:  50
[9 4 4 ... 1 0 9] [9 4 6 ... 2 0 7]
Accuracy:  0.4333170731707317
Iterations:  60
[9 4 6 ... 1 0 7] [9 4 6 ... 2 0 7]
Accuracy:  0.48034146341463413
Iterations:  70
[6 4 6 ... 1 0 7] [9 4 6 ... 2 0 7]
Accuracy:  0.5288048780487805
Iterations:  80
[6 4 6 ... 1 0 7] [9 4 6 ... 2 0 7]
Accuracy:  0.565560975609756
Iterations:  90
[6 4 6 ... 1 0 7] [9 4 6 ... 2 0 7]
Accuracy:  0.5950731707317073
Iterations:  100
[6 4 6 ... 1 0 7] [9 4 6 ... 2 0 7]
Accuracy:  0.6168048780487805
Iterations:  110
[6 4 6 ... 1 0 7] [9 4 6 ... 2 0 7]
Accuracy:  0.6350487804878049
Iterations:  

### Testing Accuracy ###

In [43]:
def make_predictions(X, W1, b1, W2, b2):
    _,_,_, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_train[:, index, None]
    prediction = make_predictions(X_train[:, index, None], W1, b1, W2, b2)
    label = y_train[index]
    
    print("prediction: ", prediction)
    print("label: ", label)

    current_image = current_image.reshape((28, 28)) * 255

    plt.gray()
    plt.imshow(current_image, interpolation='nearest')
    plt.show()

In [47]:
dev_predictions = make_predictions(X_dev, W1, b1, W2, b2)
get_accuracy(dev_predictions, y_dev)

[2 8 4 4 4 3 2 4 7 1 2 4 5 1 3 5 2 3 4 5 3 0 0 3 0 4 0 7 0 0 1 7 0 5 0 8 2
 3 0 0 4 4 2 0 5 2 0 0 4 2 3 0 3 8 5 7 3 5 4 2 5 0 2 1 0 2 1 3 2 2 3 1 5 2
 3 0 7 2 3 4 4 0 3 2 0 7 0 0 4 5 0 4 7 6 0 3 8 3 5 1 0 2 0 0 2 0 2 3 8 0 2
 3 1 0 4 2 2 3 0 1 4 1 1 1 3 1 3 0 1 0 4 5 7 0 0 3 0 4 3 4 5 4 3 0 0 0 7 8
 2 4 3 2 5 0 3 7 5 2 3 0 0 3 3 1 2 5 2 5 0 2 3 4 4 2 3 4 0 3 0 2 7 1 4 7 3
 0 1 0 7 7 3 3 3 0 4 1 0 4 1 1 0 3 1 3 3 0 1 4 4 0 0 0 0 5 3 3 1 3 0 2 2 5
 3 8 1 2 7 4 0 1 5 2 7 2 7 5 1 1 4 2 3 3 7 1 0 0 8 8 0 1 0 0 0 0 4 4 4 0 4
 1 2 0 1 0 3 4 0 3 8 7 0 2 6 0 8 4 4 2 1 3 3 3 0 4 0 2 3 0 3 3 3 4 0 3 3 4
 2 2 1 7 7 2 1 7 2 4 0 0 0 2 8 1 3 3 2 5 0 0 4 1 7 2 3 4 0 3 3 3 3 4 0 7 0
 1 4 5 5 3 2 0 0 0 0 4 2 4 7 1 7 4 0 0 4 0 4 0 4 0 1 1 4 7 7 0 1 0 7 6 3 2
 7 0 8 4 2 4 2 0 0 0 3 4 3 1 0 3 0 3 2 5 4 0 5 3 5 7 3 3 7 7 8 1 1 7 7 3 2
 3 0 5 4 4 8 3 3 5 8 2 0 1 4 2 0 0 0 3 3 0 0 2 2 3 0 3 1 3 3 1 1 5 2 1 3 0
 7 2 1 1 0 8 5 0 0 1 4 8 2 4 7 0 1 4 0 7 7 4 1 7 2 4 4 3 3 0 2 7 7 9 1 1 1
 3 4 3 3 4 3 0 0 3 5 0 8 

<ipython-input-46-dab4fd9a51d5>:12: RuntimeWarning: overflow encountered in exp
  return np.exp(Z) / np.sum(np.exp(Z))
<ipython-input-46-dab4fd9a51d5>:12: RuntimeWarning: invalid value encountered in true_divide
  return np.exp(Z) / np.sum(np.exp(Z))


0.533